[firebase]
apiKey = "AIzaSyA5cbs-FgjM-6_as4P2TllLF3jrmPBimos"
authDomain = "edugeini.firebaseapp.com"
databaseURL = "https://edugeini-default-rtdb.asia-southeast1.firebasedatabase.app"
projectId = "edugeini"
storageBucket = "edugeini.firebasestorage.app"
messagingSenderId = "1041499261965"
appId = "1:1041499261965:web:4ef2cf0d1521c741e59944"
