[firebase]
apiKey = "YOUR_FIREBASE_API_KEY"
authDomain = "..."
databaseURL = "..."
projectId = "..."
storageBucket = "..."
messagingSenderId = "..."
appId = "..."

[gco]
api_key = "YOUR_GEMINI_API_KEY"
